### ISSUE TITLE
Consider adding perl & python checks to check-broken-packages

### ISSUE THREAD

**Issue by Strykar** [desbma/pacman-hooks#1]
Would there be a measurable difference using Rust instead of these shell functions to check for packages that are broken due to outdated perl and python dependencies?

From https://github.com/maximbaz/rebuild-detector/blob/master/checkrebuild:

```
get_broken_python_pkgs() {
    command -v python >/dev/null || return
    python_version="$(python3 -c 'import sys; print (sys.version_info.minor)')"
    pacman -Qqo /usr/lib/python3.!($python_version) 2>/dev/null
}

get_broken_perl_pkgs() {
    command -v perl >/dev/null || return
    perl_version="$(perl -E 'say $^V =~ /(\d+[.]\d+)/')"
    pacman -Qqo /usr/lib/perl*/!($perl_version) 2>/dev/null
}
```
Also see this comment on running `ldd` for all files (not only binaries) owned by a package - https://github.com/maximbaz/rebuild-detector/issues/2#issuecomment-557887456

**Comment by desbma** [comment]
Hi, yes this is a good idea. I had this in the back of my head since the Python 3.8 release broke many AUR packages, and the Python release cycle will become yearly so this is a good thing to check.

This won't change performance much compared to a shell invocation, because in that case pacman does all the work with the `pacman -Qqo xxx` invocations. However since that can run in a thread while the slower `ldd` invocations are run, the wall clock time for the `check-broken-packages` will likely stay the same.

I think pacman by default already has hook to detect broken Perl packages.
Edit: see `/usr/share/libalpm/hooks/detect-old-perl-modules.hook`
