### ISSUE TITLE
check-broken-packages --exclude flag

### ISSUE THREAD

**Issue by ettom** [desbma/pacman-hooks#13]
Hi,
This is a feature request. For my use case, it would be nice if check-broken-packages allowed specifying command line flags to exclude some packages from being checked. The main issue I have with the hook is that a *lot* of messages are being generated for `haskell-language-server-static`. It would be useful to have a command line flag to specify packages to exclude from the check to avoid these false positives.

**Comment by desbma** [comment]
First things first: what are what you call false positives from `haskell-language-server-static` exactly?
Can you post the output of `check-broken-packages`?

**Comment by ettom** [comment]
Hmm, it's 500k lines long.  The first 5k or so: https://0x0.st/ok7M.txt
I think this is might be a similar issue to #10 where the package does some pretty unusual hacks. Output of `ldd` for one of the files the package provides: https://0x0.st/ok7u.txt

**Comment by desbma** [comment]
Previous issue were due to packages having libraries in non standard locations, this supposedly static package is linked to libraries which are simply not packaged. I'm surprised it even works.

I'm not sure I want to change the `check-broken-packages` hook to handle exceptions if the only use case is packages that are badly packaged or broken.

If that bothers you and you want to keep using that abomination, you can simply add this line:
```
Target = !haskell-language-server-static
```
in [/usr/share/libalpm/hooks/80-check-broken-packages.hook](https://github.com/desbma/pacman-hooks/blob/d9e76ef29d13994fef80d8aa65fbed7629b62732/check-broken-packages/check-broken-packages.hook#L4)

See https://archlinux.org/pacman/alpm-hooks.5.html#_triggers
